name: SIEM Rule Deployer

on:
  push:
    paths:
      - 'splunkrules/**'
      - 'qradarrules/**'
  workflow_dispatch:

jobs:
  deploy_all:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install pyyaml requests

      # SPLUNK DEPLOY
      - name: Deploy to Splunk
        env:
          SPLUNK_TOKEN: ${{ secrets.SPLUNK_TOKEN }}
          SPLUNK_URL: "https://13.63.91.217:8089"
        run: python deploy_rules.py

      # QRADAR DEPLOY
      - name: Deploy to QRadar
        env:
          QRADAR_TOKEN: ${{ secrets.QRADAR_TOKEN }}
          QRADAR_URL: "https://13.63.178.39" # Sənin QRadar IP-n
        run: python deploy_qradar.py
