name: Splunk Rule Deployer

on:
  push:
    paths:
      - 'splunkrules/**'
      - 'deploy_rules.py'
  workflow_dispatch: # Əllə işə salmaq üçün düymə yaradır

jobs:
  splunk_sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install pyyaml requests

      - name: Run Deploy Script
        env:
          SPLUNK_TOKEN: ${{ secrets.SPLUNK_TOKEN }}
          # Sənin AWS IP-n və Management Portu
          SPLUNK_URL: "https://13.63.91.217:8089" 
        run: python deploy_rules.py
